CREATE TABLE `auth_group` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(80) NOT NULL UNIQUE);
CREATE TABLE `auth_group_permissions` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `group_id` integer NOT NULL REFERENCES `auth_group` (`id`), `permission_id` integer NOT NULL REFERENCES `auth_permission` (`id`), UNIQUE (`group_id`, `permission_id`));
CREATE TABLE `auth_permission` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(50) NOT NULL, `content_type_id` integer NOT NULL REFERENCES `django_content_type` (`id`), `codename` varchar(100) NOT NULL, UNIQUE (`content_type_id`, `codename`));
CREATE TABLE `auth_user` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `password` varchar(128) NOT NULL, `last_login` datetime NOT NULL, `is_superuser` bool NOT NULL, `username` varchar(30) NOT NULL UNIQUE, `first_name` varchar(30) NOT NULL, `last_name` varchar(30) NOT NULL, `email` varchar(75) NOT NULL, `is_staff` bool NOT NULL, `is_active` bool NOT NULL, `date_joined` datetime NOT NULL);
CREATE TABLE `auth_user_groups` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `user_id` integer NOT NULL REFERENCES `auth_user` (`id`), `group_id` integer NOT NULL REFERENCES `auth_group` (`id`), UNIQUE (`user_id`, `group_id`));
CREATE TABLE `auth_user_user_permissions` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `user_id` integer NOT NULL REFERENCES `auth_user` (`id`), `permission_id` integer NOT NULL REFERENCES `auth_permission` (`id`), UNIQUE (`user_id`, `permission_id`));
CREATE TABLE `call_to_action_plugin_calltoactionplugin` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `block_to_show_id` integer NOT NULL REFERENCES `core_block` (`id`));
CREATE TABLE `clients_plugin_clientsplugin` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `clients_id` integer NOT NULL REFERENCES `top_gallery_gallery` (`id`));
CREATE TABLE `cms_aliaspluginmodel` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `plugin_id` integer NULL REFERENCES `cms_cmsplugin` (`id`), `alias_placeholder_id` integer NULL REFERENCES `cms_placeholder` (`id`));
CREATE TABLE `cms_cmsplugin` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `position` smallint unsigned NULL, `language` varchar(15) NOT NULL, `plugin_type` varchar(50) NOT NULL, `creation_date` datetime NOT NULL, `changed_date` datetime NOT NULL, `parent_id` integer NULL REFERENCES `cms_cmsplugin` (`id`), `placeholder_id` integer NULL REFERENCES `cms_placeholder` (`id`), `depth` integer unsigned NOT NULL, `numchild` integer unsigned NOT NULL, `path` varchar(255) NOT NULL UNIQUE);
CREATE TABLE `cms_globalpagepermission` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `can_change` bool NOT NULL, `can_add` bool NOT NULL, `can_delete` bool NOT NULL, `can_change_advanced_settings` bool NOT NULL, `can_publish` bool NOT NULL, `can_change_permissions` bool NOT NULL, `can_move_page` bool NOT NULL, `can_view` bool NOT NULL, `can_recover_page` bool NOT NULL, `group_id` integer NULL REFERENCES `auth_group` (`id`), `user_id` integer NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `cms_globalpagepermission_sites` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `site_id` integer NOT NULL REFERENCES `django_site` (`id`), `globalpagepermission_id` integer NOT NULL REFERENCES `cms_globalpagepermission` (`id`), UNIQUE (`globalpagepermission_id`, `site_id`));
CREATE TABLE `cms_page` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `changed_by` varchar(255) NOT NULL, `creation_date` datetime NOT NULL, `changed_date` datetime NOT NULL, `publication_date` datetime NULL, `publication_end_date` datetime NULL, `in_navigation` bool NOT NULL, `soft_root` bool NOT NULL, `reverse_id` varchar(40) NULL, `navigation_extenders` varchar(80) NULL, `template` varchar(100) NOT NULL, `login_required` bool NOT NULL, `limit_visibility_in_menu` smallint NULL, `is_home` bool NOT NULL, `application_urls` varchar(200) NULL, `application_namespace` varchar(200) NULL, `publisher_is_draft` bool NOT NULL, `languages` varchar(255) NULL, `revision_id` integer unsigned NOT NULL, `xframe_options` integer NOT NULL, `parent_id` integer NULL REFERENCES `cms_page` (`id`), `publisher_public_id` integer NULL UNIQUE REFERENCES `cms_page` (`id`), `site_id` integer NOT NULL REFERENCES `django_site` (`id`), `depth` integer unsigned NOT NULL, `numchild` integer unsigned NOT NULL, `path` varchar(255) NOT NULL UNIQUE, `created_by` varchar(255) NOT NULL, UNIQUE (`reverse_id`, `site_id`, `publisher_is_draft`), UNIQUE (`publisher_is_draft`, `site_id`, `application_namespace`));
CREATE TABLE `cms_page_placeholders` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `page_id` integer NOT NULL REFERENCES `cms_page` (`id`), `placeholder_id` integer NOT NULL REFERENCES `cms_placeholder` (`id`), UNIQUE (`page_id`, `placeholder_id`));
CREATE TABLE `cms_pagepermission` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `can_change` bool NOT NULL, `can_add` bool NOT NULL, `can_delete` bool NOT NULL, `can_change_advanced_settings` bool NOT NULL, `can_publish` bool NOT NULL, `can_change_permissions` bool NOT NULL, `can_move_page` bool NOT NULL, `can_view` bool NOT NULL, `grant_on` integer NOT NULL, `group_id` integer NULL REFERENCES `auth_group` (`id`), `page_id` integer NULL REFERENCES `cms_page` (`id`), `user_id` integer NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `cms_pageuser` (`user_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `auth_user` (`id`), `created_by_id` integer NOT NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `cms_pageusergroup` (`group_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `auth_group` (`id`), `created_by_id` integer NOT NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `cms_placeholder` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `slot` varchar(255) NOT NULL, `default_width` smallint unsigned NULL);
CREATE TABLE `cms_placeholderreference` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `name` varchar(255) NOT NULL, `placeholder_ref_id` integer NULL REFERENCES `cms_placeholder` (`id`));
CREATE TABLE `cms_staticplaceholder` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(255) NOT NULL, `code` varchar(255) NOT NULL, `dirty` bool NOT NULL, `creation_method` varchar(20) NOT NULL, `draft_id` integer NULL REFERENCES `cms_placeholder` (`id`), `public_id` integer NULL REFERENCES `cms_placeholder` (`id`), `site_id` integer NULL REFERENCES `django_site` (`id`), UNIQUE (`code`, `site_id`));
CREATE TABLE `cms_title` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `redirect` varchar(2048) NULL, `language` varchar(15) NOT NULL, `title` varchar(255) NOT NULL, `page_title` varchar(255) NULL, `menu_title` varchar(255) NULL, `meta_description` text NULL, `slug` varchar(255) NOT NULL, `path` varchar(255) NOT NULL, `has_url_overwrite` bool NOT NULL, `creation_date` datetime NOT NULL, `published` bool NOT NULL, `publisher_is_draft` bool NOT NULL, `publisher_state` smallint NOT NULL, `page_id` integer NOT NULL REFERENCES `cms_page` (`id`), `publisher_public_id` integer NULL UNIQUE REFERENCES `cms_title` (`id`), UNIQUE (`language`, `page_id`));
CREATE TABLE `cms_usersettings` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `language` varchar(10) NOT NULL, `clipboard_id` integer NULL REFERENCES `cms_placeholder` (`id`), `user_id` integer NOT NULL UNIQUE REFERENCES `auth_user` (`id`));
CREATE TABLE `cmsplugin_filer_file_filerfile` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `title` varchar(255) NULL, `target_blank` bool NOT NULL, `style` varchar(255) NOT NULL, `file_id` integer NOT NULL REFERENCES `filer_file` (`id`));
CREATE TABLE `cmsplugin_filer_folder_filerfolder` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `title` varchar(255) NULL, `style` varchar(50) NOT NULL, `folder_id` integer NOT NULL REFERENCES `filer_folder` (`id`));
CREATE TABLE `cmsplugin_filer_image_filerimage` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `style` varchar(50) NOT NULL, `caption_text` varchar(255) NULL, `image_url` varchar(200) NULL, `alt_text` varchar(255) NULL, `use_original_image` bool NOT NULL, `use_autoscale` bool NOT NULL, `width` integer unsigned NULL, `height` integer unsigned NULL, `crop` bool NOT NULL, `upscale` bool NOT NULL, `alignment` varchar(10) NULL, `free_link` varchar(255) NULL, `original_link` bool NOT NULL, `description` text NULL, `target_blank` bool NOT NULL, `file_link_id` integer NULL REFERENCES `filer_file` (`id`), `image_id` integer NULL REFERENCES `filer_image` (`file_ptr_id`), `page_link_id` integer NULL REFERENCES `cms_page` (`id`), `thumbnail_option_id` integer NULL REFERENCES `cmsplugin_filer_image_thumbnailoption` (`id`));
CREATE TABLE `cmsplugin_filer_image_thumbnailoption` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(100) NOT NULL, `width` integer NOT NULL, `height` integer NOT NULL, `crop` bool NOT NULL, `upscale` bool NOT NULL);
CREATE TABLE `cmsplugin_filer_teaser_filerteaser` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `title` varchar(255) NOT NULL, `image_url` varchar(200) NULL, `style` varchar(255) NOT NULL, `use_autoscale` bool NOT NULL, `width` integer unsigned NULL, `height` integer unsigned NULL, `free_link` varchar(255) NULL, `description` text NULL, `target_blank` bool NOT NULL, `image_id` integer NULL REFERENCES `filer_image` (`file_ptr_id`), `page_link_id` integer NULL REFERENCES `cms_page` (`id`));
CREATE TABLE `cmsplugin_filer_video_filervideo` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `movie_url` varchar(255) NULL, `width` smallint unsigned NOT NULL, `height` smallint unsigned NOT NULL, `auto_play` bool NOT NULL, `auto_hide` bool NOT NULL, `fullscreen` bool NOT NULL, `loop` bool NOT NULL, `bgcolor` varchar(6) NOT NULL, `textcolor` varchar(6) NOT NULL, `seekbarcolor` varchar(6) NOT NULL, `seekbarbgcolor` varchar(6) NOT NULL, `loadingbarcolor` varchar(6) NOT NULL, `buttonoutcolor` varchar(6) NOT NULL, `buttonovercolor` varchar(6) NOT NULL, `buttonhighlightcolor` varchar(6) NOT NULL, `image_id` integer NULL REFERENCES `filer_image` (`file_ptr_id`), `movie_id` integer NULL REFERENCES `filer_file` (`id`));
CREATE TABLE `core_block` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `subtitle` varchar(300) NOT NULL, `title` varchar(200) NOT NULL, `button_title` varchar(100) NOT NULL, `button_link` varchar(100) NOT NULL);
CREATE TABLE `django_admin_log` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `action_time` datetime NOT NULL, `object_id` text NULL, `object_repr` varchar(200) NOT NULL, `action_flag` smallint unsigned NOT NULL, `change_message` text NOT NULL, `content_type_id` integer NULL REFERENCES `django_content_type` (`id`), `user_id` integer NOT NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `django_content_type` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(100) NOT NULL, `app_label` varchar(100) NOT NULL, `model` varchar(100) NOT NULL, UNIQUE (`app_label`, `model`));
CREATE TABLE `django_migrations` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL);
CREATE TABLE `django_session` (`session_key` varchar(40) NOT NULL PRIMARY KEY, `session_data` text NOT NULL, `expire_date` datetime NOT NULL);
CREATE TABLE `django_site` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `domain` varchar(100) NOT NULL, `name` varchar(50) NOT NULL);
CREATE TABLE `djangocms_blog_authorentriesplugin` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `latest_posts` integer NOT NULL);
CREATE TABLE `djangocms_blog_authorentriesplugin_authors` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `user_id` integer NOT NULL REFERENCES `auth_user` (`id`), `authorentriesplugin_id` integer NOT NULL REFERENCES `djangocms_blog_authorentriesplugin` (`cmsplugin_ptr_id`), UNIQUE (`authorentriesplugin_id`, `user_id`));
CREATE TABLE `djangocms_blog_blogcategory` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `date_created` datetime NOT NULL, `date_modified` datetime NOT NULL, `parent_id` integer NULL REFERENCES `djangocms_blog_blogcategory` (`id`));
CREATE TABLE `djangocms_blog_blogcategory_translation` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(255) NOT NULL, `slug` varchar(50) NOT NULL, `master_id` integer NULL REFERENCES `djangocms_blog_blogcategory` (`id`), `language_code` varchar(15) NOT NULL, UNIQUE (`language_code`, `slug`), UNIQUE (`language_code`, `master_id`));
CREATE TABLE `djangocms_blog_latestpostsplugin` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `latest_posts` integer NOT NULL);
CREATE TABLE `djangocms_blog_latestpostsplugin_categories` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `latestpostsplugin_id` integer NOT NULL REFERENCES `djangocms_blog_latestpostsplugin` (`cmsplugin_ptr_id`), `blogcategory_id` integer NOT NULL REFERENCES `djangocms_blog_blogcategory` (`id`), UNIQUE (`latestpostsplugin_id`, `blogcategory_id`));
CREATE TABLE `djangocms_blog_latestpostsplugin_tags` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `latestpostsplugin_id` integer NOT NULL REFERENCES `djangocms_blog_latestpostsplugin` (`cmsplugin_ptr_id`), `tag_id` integer NOT NULL REFERENCES `taggit_tag` (`id`), UNIQUE (`latestpostsplugin_id`, `tag_id`));
CREATE TABLE `djangocms_blog_post` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `date_created` datetime NOT NULL, `date_modified` datetime NOT NULL, `date_published` datetime NOT NULL, `date_published_end` datetime NULL, `enable_comments` bool NOT NULL, `author_id` integer NULL REFERENCES `auth_user` (`id`), `content_id` integer NULL REFERENCES `cms_placeholder` (`id`), `main_image_id` integer NULL REFERENCES `filer_image` (`file_ptr_id`), `main_image_full_id` integer NULL REFERENCES `cmsplugin_filer_image_thumbnailoption` (`id`), `main_image_thumbnail_id` integer NULL REFERENCES `cmsplugin_filer_image_thumbnailoption` (`id`), `publish` bool NOT NULL);
CREATE TABLE `djangocms_blog_post_categories` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `post_id` integer NOT NULL REFERENCES `djangocms_blog_post` (`id`), `blogcategory_id` integer NOT NULL REFERENCES `djangocms_blog_blogcategory` (`id`), UNIQUE (`post_id`, `blogcategory_id`));
CREATE TABLE `djangocms_blog_post_sites` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `site_id` integer NOT NULL REFERENCES `django_site` (`id`), `post_id` integer NOT NULL REFERENCES `djangocms_blog_post` (`id`), UNIQUE (`post_id`, `site_id`));
CREATE TABLE `djangocms_blog_post_translation` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `abstract` text NOT NULL, `language_code` varchar(15) NOT NULL, `title` varchar(255) NOT NULL, `slug` varchar(50) NOT NULL, `meta_description` text NOT NULL, `meta_keywords` text NOT NULL, `meta_title` varchar(255) NOT NULL, `post_text` text NOT NULL, `master_id` integer NULL REFERENCES `djangocms_blog_post` (`id`), UNIQUE (`language_code`, `master_id`), UNIQUE (`language_code`, `slug`));
CREATE TABLE `djangocms_column_column` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `width` varchar(50) NOT NULL);
CREATE TABLE `djangocms_column_multicolumns` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`));
CREATE TABLE `djangocms_flash_flash` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `file` varchar(100) NOT NULL, `width` varchar(6) NOT NULL, `height` varchar(6) NOT NULL);
CREATE TABLE `djangocms_googlemap_googlemap` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `title` varchar(100) NULL, `address` varchar(150) NOT NULL, `zipcode` varchar(30) NOT NULL, `city` varchar(100) NOT NULL, `content` varchar(255) NOT NULL, `zoom` smallint unsigned NOT NULL, `lat` decimal NULL, `lng` decimal NULL, `route_planer_title` varchar(150) NULL, `route_planer` bool NOT NULL, `width` varchar(6) NOT NULL, `height` varchar(6) NOT NULL, `info_window` bool NOT NULL, `scrollwheel` bool NOT NULL, `double_click_zoom` bool NOT NULL, `draggable` bool NOT NULL, `keyboard_shortcuts` bool NOT NULL, `pan_control` bool NOT NULL, `zoom_control` bool NOT NULL, `street_view_control` bool NOT NULL);
CREATE TABLE `djangocms_inherit_inheritpageplaceholder` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `from_language` varchar(5) NULL, `from_page_id` integer NULL REFERENCES `cms_page` (`id`));
CREATE TABLE `djangocms_link_link` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `name` varchar(256) NOT NULL, `anchor` varchar(128) NOT NULL, `mailto` varchar(75) NULL, `phone` varchar(40) NULL, `target` varchar(100) NOT NULL, `page_link_id` integer NULL REFERENCES `cms_page` (`id`), `url` varchar(2048) NULL);
CREATE TABLE `djangocms_style_style` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `class_name` varchar(50) NULL, `tag_type` varchar(50) NOT NULL, `padding_left` smallint NULL, `padding_right` smallint NULL, `padding_top` smallint NULL, `padding_bottom` smallint NULL, `margin_left` smallint NULL, `margin_right` smallint NULL, `margin_top` smallint NULL, `margin_bottom` smallint NULL, `additional_classes` varchar(200) NOT NULL);
CREATE TABLE `djangocms_text_ckeditor_text` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `body` text NOT NULL);
CREATE TABLE `easy_thumbnails_source` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `storage_hash` varchar(40) NOT NULL, `name` varchar(255) NOT NULL, `modified` datetime NOT NULL, UNIQUE (`storage_hash`, `name`));
CREATE TABLE `easy_thumbnails_thumbnail` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `storage_hash` varchar(40) NOT NULL, `name` varchar(255) NOT NULL, `modified` datetime NOT NULL, `source_id` integer NOT NULL REFERENCES `easy_thumbnails_source` (`id`), UNIQUE (`storage_hash`, `name`, `source_id`));
CREATE TABLE `easy_thumbnails_thumbnaildimensions` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `thumbnail_id` integer NOT NULL UNIQUE REFERENCES `easy_thumbnails_thumbnail` (`id`), `width` integer unsigned NULL, `height` integer unsigned NULL);
CREATE TABLE `filer_clipboard` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `user_id` integer NOT NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `filer_clipboarditem` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `clipboard_id` integer NOT NULL REFERENCES `filer_clipboard` (`id`), `file_id` integer NOT NULL REFERENCES `filer_file` (`id`));
CREATE TABLE `filer_file` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `polymorphic_ctype_id` integer NULL REFERENCES `django_content_type` (`id`), `file` varchar(255) NULL, `_file_size` integer NULL, `sha1` varchar(40) NOT NULL, `has_all_mandatory_data` bool NOT NULL, `original_filename` varchar(255) NULL, `name` varchar(255) NOT NULL, `description` text NULL, `uploaded_at` datetime NOT NULL, `modified_at` datetime NOT NULL, `is_public` bool NOT NULL, `folder_id` integer NULL REFERENCES `filer_folder` (`id`), `owner_id` integer NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `filer_folder` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(255) NOT NULL, `uploaded_at` datetime NOT NULL, `created_at` datetime NOT NULL, `modified_at` datetime NOT NULL, `lft` integer unsigned NOT NULL, `rght` integer unsigned NOT NULL, `tree_id` integer unsigned NOT NULL, `level` integer unsigned NOT NULL, `owner_id` integer NULL REFERENCES `auth_user` (`id`), `parent_id` integer NULL REFERENCES `filer_folder` (`id`), UNIQUE (`parent_id`, `name`));
CREATE TABLE `filer_folderpermission` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `type` smallint NOT NULL, `everybody` bool NOT NULL, `can_edit` smallint NULL, `can_read` smallint NULL, `can_add_children` smallint NULL, `folder_id` integer NULL REFERENCES `filer_folder` (`id`), `group_id` integer NULL REFERENCES `auth_group` (`id`), `user_id` integer NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `filer_image` (`file_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `filer_file` (`id`), `_height` integer NULL, `_width` integer NULL, `date_taken` datetime NULL, `default_alt_text` varchar(255) NULL, `default_caption` varchar(255) NULL, `author` varchar(255) NULL, `must_always_publish_author_credit` bool NOT NULL, `must_always_publish_copyright` bool NOT NULL, `subject_location` varchar(64) NULL);
CREATE TABLE `menus_cachekey` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `language` varchar(255) NOT NULL, `site` integer unsigned NOT NULL, `key` varchar(255) NOT NULL);
CREATE TABLE `reversion_revision` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `manager_slug` varchar(200) NOT NULL, `date_created` datetime NOT NULL, `comment` text NOT NULL, `user_id` integer NULL REFERENCES `auth_user` (`id`));
CREATE TABLE `reversion_version` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `object_id` text NOT NULL, `object_id_int` integer NULL, `format` varchar(255) NOT NULL, `serialized_data` text NOT NULL, `object_repr` text NOT NULL, `content_type_id` integer NOT NULL REFERENCES `django_content_type` (`id`), `revision_id` integer NOT NULL REFERENCES `reversion_revision` (`id`));
CREATE TABLE `taggit_tag` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(100) NOT NULL UNIQUE, `slug` varchar(100) NOT NULL UNIQUE);
CREATE TABLE `taggit_taggeditem` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `object_id` integer NOT NULL, `content_type_id` integer NOT NULL REFERENCES `django_content_type` (`id`), `tag_id` integer NOT NULL REFERENCES `taggit_tag` (`id`));
CREATE TABLE `top_gallery_gallery` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `name` varchar(128) NOT NULL);
CREATE TABLE `top_gallery_photo` (`id` integer NOT NULL PRIMARY KEY AUTO_INCREMENT, `title` varchar(128) NULL, `file` varchar(100) NOT NULL, `gallery_id` integer NOT NULL REFERENCES `top_gallery_gallery` (`id`));
CREATE TABLE `top_gallery_plugin_topgalleryplugin` (`cmsplugin_ptr_id` integer NOT NULL PRIMARY KEY REFERENCES `cms_cmsplugin` (`id`), `gallery_id` integer NOT NULL REFERENCES `top_gallery_gallery` (`id`));
CREATE INDEX `auth_group_permissions_0e939a4f` ON `auth_group_permissions` (`group_id`);
CREATE INDEX `auth_group_permissions_8373b171` ON `auth_group_permissions` (`permission_id`);
CREATE INDEX `auth_permission_417f1b1c` ON `auth_permission` (`content_type_id`);
CREATE INDEX `auth_user_groups_0e939a4f` ON `auth_user_groups` (`group_id`);
CREATE INDEX `auth_user_groups_e8701ad4` ON `auth_user_groups` (`user_id`);
CREATE INDEX `auth_user_user_permissions_8373b171` ON `auth_user_user_permissions` (`permission_id`);
CREATE INDEX `auth_user_user_permissions_e8701ad4` ON `auth_user_user_permissions` (`user_id`);
CREATE INDEX `call_to_action_plugin_calltoactionplugin_2e77d208` ON `call_to_action_plugin_calltoactionplugin` (`block_to_show_id`);
CREATE INDEX `clients_plugin_clientsplugin_4e790517` ON `clients_plugin_clientsplugin` (`clients_id`);
CREATE INDEX `cms_aliaspluginmodel_921abf5c` ON `cms_aliaspluginmodel` (`alias_placeholder_id`);
CREATE INDEX `cms_aliaspluginmodel_b25eaab4` ON `cms_aliaspluginmodel` (`plugin_id`);
CREATE INDEX `cms_cmsplugin_667a6151` ON `cms_cmsplugin` (`placeholder_id`);
CREATE INDEX `cms_cmsplugin_6be37982` ON `cms_cmsplugin` (`parent_id`);
CREATE INDEX `cms_cmsplugin_8512ae7d` ON `cms_cmsplugin` (`language`);
CREATE INDEX `cms_cmsplugin_b5e4cf8f` ON `cms_cmsplugin` (`plugin_type`);
CREATE INDEX `cms_globalpagepermission_0e939a4f` ON `cms_globalpagepermission` (`group_id`);
CREATE INDEX `cms_globalpagepermission_e8701ad4` ON `cms_globalpagepermission` (`user_id`);
CREATE INDEX `cms_globalpagepermission_sites_9365d6e7` ON `cms_globalpagepermission_sites` (`site_id`);
CREATE INDEX `cms_globalpagepermission_sites_a3d12ecd` ON `cms_globalpagepermission_sites` (`globalpagepermission_id`);
CREATE INDEX `cms_page_1d85575d` ON `cms_page` (`soft_root`);
CREATE INDEX `cms_page_2247c5f0` ON `cms_page` (`publication_end_date`);
CREATE INDEX `cms_page_3d9ef52f` ON `cms_page` (`reverse_id`);
CREATE INDEX `cms_page_4fa1c803` ON `cms_page` (`is_home`);
CREATE INDEX `cms_page_6be37982` ON `cms_page` (`parent_id`);
CREATE INDEX `cms_page_7b8acfa6` ON `cms_page` (`navigation_extenders`);
CREATE INDEX `cms_page_9365d6e7` ON `cms_page` (`site_id`);
CREATE INDEX `cms_page_93b83098` ON `cms_page` (`publication_date`);
CREATE INDEX `cms_page_b7700099` ON `cms_page` (`publisher_is_draft`);
CREATE INDEX `cms_page_cb540373` ON `cms_page` (`limit_visibility_in_menu`);
CREATE INDEX `cms_page_db3eb53f` ON `cms_page` (`in_navigation`);
CREATE INDEX `cms_page_e721871e` ON `cms_page` (`application_urls`);
CREATE INDEX `cms_pagepermission_0e939a4f` ON `cms_pagepermission` (`group_id`);
CREATE INDEX `cms_pagepermission_1a63c800` ON `cms_pagepermission` (`page_id`);
CREATE INDEX `cms_pagepermission_e8701ad4` ON `cms_pagepermission` (`user_id`);
CREATE INDEX `cms_placeholder_5e97994e` ON `cms_placeholder` (`slot`);
CREATE INDEX `cms_placeholderreference_328d0afc` ON `cms_placeholderreference` (`placeholder_ref_id`);
CREATE INDEX `cms_staticplaceholder_1ee2744d` ON `cms_staticplaceholder` (`public_id`);
CREATE INDEX `cms_staticplaceholder_5cb48773` ON `cms_staticplaceholder` (`draft_id`);
CREATE INDEX `cms_staticplaceholder_9365d6e7` ON `cms_staticplaceholder` (`site_id`);
CREATE INDEX `cms_title_1268de9a` ON `cms_title` (`has_url_overwrite`);
CREATE INDEX `cms_title_1a63c800` ON `cms_title` (`page_id`);
CREATE INDEX `cms_title_2dbcba41` ON `cms_title` (`slug`);
CREATE INDEX `cms_title_8512ae7d` ON `cms_title` (`language`);
CREATE INDEX `cms_title_b7700099` ON `cms_title` (`publisher_is_draft`);
CREATE INDEX `cms_title_d6fe1d0b` ON `cms_title` (`path`);
CREATE INDEX `cms_title_f7202fc0` ON `cms_title` (`publisher_state`);
CREATE INDEX `cms_usersettings_2655b062` ON `cms_usersettings` (`clipboard_id`);
CREATE INDEX `cmsplugin_filer_file_filerfile_814552b9` ON `cmsplugin_filer_file_filerfile` (`file_id`);
CREATE INDEX `cmsplugin_filer_folder_filerfolder_a8a44dbb` ON `cmsplugin_filer_folder_filerfolder` (`folder_id`);
CREATE INDEX `cmsplugin_filer_image_filerimage_0fe0fc57` ON `cmsplugin_filer_image_filerimage` (`file_link_id`);
CREATE INDEX `cmsplugin_filer_image_filerimage_6b85b7b1` ON `cmsplugin_filer_image_filerimage` (`thumbnail_option_id`);
CREATE INDEX `cmsplugin_filer_image_filerimage_d916d256` ON `cmsplugin_filer_image_filerimage` (`page_link_id`);
CREATE INDEX `cmsplugin_filer_image_filerimage_f33175e6` ON `cmsplugin_filer_image_filerimage` (`image_id`);
CREATE INDEX `cmsplugin_filer_teaser_filerteaser_d916d256` ON `cmsplugin_filer_teaser_filerteaser` (`page_link_id`);
CREATE INDEX `cmsplugin_filer_teaser_filerteaser_f33175e6` ON `cmsplugin_filer_teaser_filerteaser` (`image_id`);
CREATE INDEX `cmsplugin_filer_video_filervideo_d1b173c8` ON `cmsplugin_filer_video_filervideo` (`movie_id`);
CREATE INDEX `cmsplugin_filer_video_filervideo_f33175e6` ON `cmsplugin_filer_video_filervideo` (`image_id`);
CREATE INDEX `django_admin_log_417f1b1c` ON `django_admin_log` (`content_type_id`);
CREATE INDEX `django_admin_log_e8701ad4` ON `django_admin_log` (`user_id`);
CREATE INDEX `django_session_de54fa62` ON `django_session` (`expire_date`);
CREATE INDEX `djangocms_blog_authorentriesplugin_authors_793c8338` ON `djangocms_blog_authorentriesplugin_authors` (`authorentriesplugin_id`);
CREATE INDEX `djangocms_blog_authorentriesplugin_authors_e8701ad4` ON `djangocms_blog_authorentriesplugin_authors` (`user_id`);
CREATE INDEX `djangocms_blog_blogcategory_6be37982` ON `djangocms_blog_blogcategory` (`parent_id`);
CREATE INDEX `djangocms_blog_blogcategory_translation_2dbcba41` ON `djangocms_blog_blogcategory_translation` (`slug`);
CREATE INDEX `djangocms_blog_blogcategory_translation_60716c2f` ON `djangocms_blog_blogcategory_translation` (`language_code`);
CREATE INDEX `djangocms_blog_blogcategory_translation_90349b61` ON `djangocms_blog_blogcategory_translation` (`master_id`);
CREATE INDEX `djangocms_blog_latestpostsplugin_categories_efb54956` ON `djangocms_blog_latestpostsplugin_categories` (`blogcategory_id`);
CREATE INDEX `djangocms_blog_latestpostsplugin_categories_fda89e10` ON `djangocms_blog_latestpostsplugin_categories` (`latestpostsplugin_id`);
CREATE INDEX `djangocms_blog_latestpostsplugin_tags_76f094bc` ON `djangocms_blog_latestpostsplugin_tags` (`tag_id`);
CREATE INDEX `djangocms_blog_latestpostsplugin_tags_fda89e10` ON `djangocms_blog_latestpostsplugin_tags` (`latestpostsplugin_id`);
CREATE INDEX `djangocms_blog_post_36b62cbe` ON `djangocms_blog_post` (`main_image_id`);
CREATE INDEX `djangocms_blog_post_4f331e2f` ON `djangocms_blog_post` (`author_id`);
CREATE INDEX `djangocms_blog_post_53808359` ON `djangocms_blog_post` (`main_image_full_id`);
CREATE INDEX `djangocms_blog_post_9d0a35cc` ON `djangocms_blog_post` (`main_image_thumbnail_id`);
CREATE INDEX `djangocms_blog_post_categories_efb54956` ON `djangocms_blog_post_categories` (`blogcategory_id`);
CREATE INDEX `djangocms_blog_post_categories_f3aa1999` ON `djangocms_blog_post_categories` (`post_id`);
CREATE INDEX `djangocms_blog_post_e14f02ad` ON `djangocms_blog_post` (`content_id`);
CREATE INDEX `djangocms_blog_post_sites_9365d6e7` ON `djangocms_blog_post_sites` (`site_id`);
CREATE INDEX `djangocms_blog_post_sites_f3aa1999` ON `djangocms_blog_post_sites` (`post_id`);
CREATE INDEX `djangocms_blog_post_translation_2dbcba41` ON `djangocms_blog_post_translation` (`slug`);
CREATE INDEX `djangocms_blog_post_translation_60716c2f` ON `djangocms_blog_post_translation` (`language_code`);
CREATE INDEX `djangocms_blog_post_translation_90349b61` ON `djangocms_blog_post_translation` (`master_id`);
CREATE INDEX `djangocms_inherit_inheritpageplaceholder_ccbb37bf` ON `djangocms_inherit_inheritpageplaceholder` (`from_page_id`);
CREATE INDEX `djangocms_link_link_d916d256` ON `djangocms_link_link` (`page_link_id`);
CREATE INDEX `easy_thumbnails_source_b068931c` ON `easy_thumbnails_source` (`name`);
CREATE INDEX `easy_thumbnails_source_b454e115` ON `easy_thumbnails_source` (`storage_hash`);
CREATE INDEX `easy_thumbnails_thumbnail_0afd9202` ON `easy_thumbnails_thumbnail` (`source_id`);
CREATE INDEX `easy_thumbnails_thumbnail_b068931c` ON `easy_thumbnails_thumbnail` (`name`);
CREATE INDEX `easy_thumbnails_thumbnail_b454e115` ON `easy_thumbnails_thumbnail` (`storage_hash`);
CREATE INDEX `filer_clipboard_e8701ad4` ON `filer_clipboard` (`user_id`);
CREATE INDEX `filer_clipboarditem_2655b062` ON `filer_clipboarditem` (`clipboard_id`);
CREATE INDEX `filer_clipboarditem_814552b9` ON `filer_clipboarditem` (`file_id`);
CREATE INDEX `filer_file_5e7b1936` ON `filer_file` (`owner_id`);
CREATE INDEX `filer_file_a8a44dbb` ON `filer_file` (`folder_id`);
CREATE INDEX `filer_file_d3e32c49` ON `filer_file` (`polymorphic_ctype_id`);
CREATE INDEX `filer_folder_3cfbd988` ON `filer_folder` (`rght`);
CREATE INDEX `filer_folder_5e7b1936` ON `filer_folder` (`owner_id`);
CREATE INDEX `filer_folder_656442a0` ON `filer_folder` (`tree_id`);
CREATE INDEX `filer_folder_6be37982` ON `filer_folder` (`parent_id`);
CREATE INDEX `filer_folder_c9e9a848` ON `filer_folder` (`level`);
CREATE INDEX `filer_folder_caf7cc51` ON `filer_folder` (`lft`);
CREATE INDEX `reversion_revision_b16b0f06` ON `reversion_revision` (`manager_slug`);
CREATE INDEX `reversion_revision_c69e55a4` ON `reversion_revision` (`date_created`);
CREATE INDEX `reversion_revision_e8701ad4` ON `reversion_revision` (`user_id`);
CREATE INDEX `reversion_version_0c9ba3a3` ON `reversion_version` (`object_id_int`);
CREATE INDEX `reversion_version_417f1b1c` ON `reversion_version` (`content_type_id`);
CREATE INDEX `reversion_version_5de09a8d` ON `reversion_version` (`revision_id`);
CREATE INDEX `taggit_taggeditem_417f1b1c` ON `taggit_taggeditem` (`content_type_id`);
CREATE INDEX `taggit_taggeditem_76f094bc` ON `taggit_taggeditem` (`tag_id`);
CREATE INDEX `taggit_taggeditem_af31437c` ON `taggit_taggeditem` (`object_id`);
CREATE INDEX `taggit_taggeditem_content_type_id_c5245e950b1257d_idx` ON `taggit_taggeditem` (`content_type_id`, `object_id`);
CREATE INDEX `top_gallery_photo_6d994cdb` ON `top_gallery_photo` (`gallery_id`);
CREATE INDEX `top_gallery_plugin_topgalleryplugin_6d994cdb` ON `top_gallery_plugin_topgalleryplugin` (`gallery_id`);
