# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav_one', '0002_auto_20160411_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_site', to='sites.Site', verbose_name='site'),
        ),
    ]
