# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eav_one', '0003_auto_20160413_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_site', to='sites.Site', verbose_name='site'),
        ),
    ]
