# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdxProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('expire_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='FormGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('data_attribute', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to=b'uploads/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_draft', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, upload_to=b'images')),
                ('edx_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionary_one.EdxProject')),
            ],
        ),
        migrations.AddField(
            model_name='formgallery',
            name='formstep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionary_one.FormStep'),
        ),
    ]
