# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionary', '0006_auto_20160512_1751'),
        ('questionary', '0006_auto_20151117_1128'),
    ]

    operations = [
    ]
