# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_gallery', '0006_testinonials_client_organisation'),
        ('top_gallery', '0009_merge'),
    ]

    operations = [
    ]
